### ISSUE TITLE
is repo DEAD ?

### ISSUE THREAD

**Issue by keradus** [klaussilveira/gitter#59]
there is 1 **year** old bugfix ready for merge - #52

**Comment by keradus** [comment]
I'm not using this library anymore. 
I have no reason to believe that fork will be maintained over time or community will use forked version instead of root one. If you want to help maintaining the package raise your idea to repo owner.
On your fork I see randomly pushed commits to master, which is bad approach...

**Comment by keradus** [comment]
@klaussilveira , could you archive this repo (in repo settings, bottom of main view) ?
it's not maintained anymore

**Comment by keradus** [comment]
@p3x-robot , totally not related.
1. you are talking about fork !
2. you are talking about fork of other repo !
I told you, if you want to officially take management, contact with repo owner.

In the meantime, I'm asking him to archive the repo.

**Comment by keradus** [comment]
@klaussilveira , could you archive this repo (in repo settings, bottom of main view) ?
it's not maintained anymore

**Comment by klaussilveira** [comment]
Just because we're not adding features every month, doesn't mean the project is dead. It is stable enough and does it's job: it's a web repository viewer.

**Comment by keradus** [comment]
@klaussilveira , you are talking about repo viewer - `gitlist`. you got confused by p3x

This is `gitter`, the php lib to operate with git.
If it's not dead, please merge fixes, like one **2 years ago** (!!!!!!!!!) i raised bug and fix for it, no answer at all:
https://github.com/klaussilveira/gitter/pull/52

**Comment by keradus** [comment]
p3x, please stop spamming
